// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AppConfig {
  final int oscPort;
  final String? deviceName;
  final int bufferSize;
  final String themeStartOscAddress;
  final String systemResetOscAddress;
  final Map<int, ChannelSetting> monoConfigs;
  final Map<int, ChannelSetting> stereoConfigs;
  final Map<int, ChannelSetting> multiConfigs;
  final List<RoomConfig> rooms;
  final bool isExhibitionMode;

  const AppConfig({
    required this.oscPort,
    this.deviceName,
    required this.bufferSize,
    required this.themeStartOscAddress,
    required this.systemResetOscAddress,
    required this.monoConfigs,
    required this.stereoConfigs,
    required this.multiConfigs,
    required this.rooms,
    required this.isExhibitionMode,
  });

  @override
  int get hashCode =>
      oscPort.hashCode ^
      deviceName.hashCode ^
      bufferSize.hashCode ^
      themeStartOscAddress.hashCode ^
      systemResetOscAddress.hashCode ^
      monoConfigs.hashCode ^
      stereoConfigs.hashCode ^
      multiConfigs.hashCode ^
      rooms.hashCode ^
      isExhibitionMode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppConfig &&
          runtimeType == other.runtimeType &&
          oscPort == other.oscPort &&
          deviceName == other.deviceName &&
          bufferSize == other.bufferSize &&
          themeStartOscAddress == other.themeStartOscAddress &&
          systemResetOscAddress == other.systemResetOscAddress &&
          monoConfigs == other.monoConfigs &&
          stereoConfigs == other.stereoConfigs &&
          multiConfigs == other.multiConfigs &&
          rooms == other.rooms &&
          isExhibitionMode == other.isExhibitionMode;
}

class ChannelSetting {
  final bool enabled;
  final String customName;
  final double delayMs;
  final List<EqBand> eqBands;

  const ChannelSetting({
    required this.enabled,
    required this.customName,
    required this.delayMs,
    required this.eqBands,
  });

  @override
  int get hashCode =>
      enabled.hashCode ^
      customName.hashCode ^
      delayMs.hashCode ^
      eqBands.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChannelSetting &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          customName == other.customName &&
          delayMs == other.delayMs &&
          eqBands == other.eqBands;
}

class EqBand {
  final bool enabled;
  final double freq;
  final double gain;
  final double qFactor;
  final EqType filterType;

  const EqBand({
    required this.enabled,
    required this.freq,
    required this.gain,
    required this.qFactor,
    required this.filterType,
  });

  @override
  int get hashCode =>
      enabled.hashCode ^
      freq.hashCode ^
      gain.hashCode ^
      qFactor.hashCode ^
      filterType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EqBand &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          freq == other.freq &&
          gain == other.gain &&
          qFactor == other.qFactor &&
          filterType == other.filterType;
}

enum EqType { lowCut, lowShelf, bell, notch, highShelf, highCut }

class RoomConfig {
  final String id;
  final String name;
  final String colorHex;
  final double volume;
  final String clearOscAddress;
  final List<TrackConfig> tracks;

  const RoomConfig({
    required this.id,
    required this.name,
    required this.colorHex,
    required this.volume,
    required this.clearOscAddress,
    required this.tracks,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      colorHex.hashCode ^
      volume.hashCode ^
      clearOscAddress.hashCode ^
      tracks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomConfig &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          colorHex == other.colorHex &&
          volume == other.volume &&
          clearOscAddress == other.clearOscAddress &&
          tracks == other.tracks;
}

class TrackConfig {
  final String id;
  final String name;
  final String filePath;
  final double volume;
  final bool isLoop;
  final int outputChannel;
  final bool outputStereo;
  final String playOscAddress;
  final String stopOscAddress;

  const TrackConfig({
    required this.id,
    required this.name,
    required this.filePath,
    required this.volume,
    required this.isLoop,
    required this.outputChannel,
    required this.outputStereo,
    required this.playOscAddress,
    required this.stopOscAddress,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      filePath.hashCode ^
      volume.hashCode ^
      isLoop.hashCode ^
      outputChannel.hashCode ^
      outputStereo.hashCode ^
      playOscAddress.hashCode ^
      stopOscAddress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackConfig &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          filePath == other.filePath &&
          volume == other.volume &&
          isLoop == other.isLoop &&
          outputChannel == other.outputChannel &&
          outputStereo == other.outputStereo &&
          playOscAddress == other.playOscAddress &&
          stopOscAddress == other.stopOscAddress;
}
