// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AppConfig {
  final int oscPort;
  final String? deviceName;
  final int bufferSize;
  final String themeStartOscAddress;
  final String systemResetOscAddress;
  final String? trackingOscAddress;
  final Map<int, ChannelSetting> monoConfigs;
  final Map<int, ChannelSetting> stereoConfigs;
  final Map<int, ChannelSetting> multiConfigs;
  final List<RoomConfig> rooms;
  final Trajectory? globalTrajectory;
  final List<RoomZone> roomZones;
  final bool isExhibitionMode;
  final double masterHeadroomDb;
  final bool peakLimiterEnabled;

  const AppConfig({
    required this.oscPort,
    this.deviceName,
    required this.bufferSize,
    required this.themeStartOscAddress,
    required this.systemResetOscAddress,
    this.trackingOscAddress,
    required this.monoConfigs,
    required this.stereoConfigs,
    required this.multiConfigs,
    required this.rooms,
    this.globalTrajectory,
    required this.roomZones,
    required this.isExhibitionMode,
    required this.masterHeadroomDb,
    required this.peakLimiterEnabled,
  });

  @override
  int get hashCode =>
      oscPort.hashCode ^
      deviceName.hashCode ^
      bufferSize.hashCode ^
      themeStartOscAddress.hashCode ^
      systemResetOscAddress.hashCode ^
      trackingOscAddress.hashCode ^
      monoConfigs.hashCode ^
      stereoConfigs.hashCode ^
      multiConfigs.hashCode ^
      rooms.hashCode ^
      globalTrajectory.hashCode ^
      roomZones.hashCode ^
      isExhibitionMode.hashCode ^
      masterHeadroomDb.hashCode ^
      peakLimiterEnabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppConfig &&
          runtimeType == other.runtimeType &&
          oscPort == other.oscPort &&
          deviceName == other.deviceName &&
          bufferSize == other.bufferSize &&
          themeStartOscAddress == other.themeStartOscAddress &&
          systemResetOscAddress == other.systemResetOscAddress &&
          trackingOscAddress == other.trackingOscAddress &&
          monoConfigs == other.monoConfigs &&
          stereoConfigs == other.stereoConfigs &&
          multiConfigs == other.multiConfigs &&
          rooms == other.rooms &&
          globalTrajectory == other.globalTrajectory &&
          roomZones == other.roomZones &&
          isExhibitionMode == other.isExhibitionMode &&
          masterHeadroomDb == other.masterHeadroomDb &&
          peakLimiterEnabled == other.peakLimiterEnabled;
}

class ChannelSetting {
  final bool enabled;
  final String customName;
  final double delayMs;
  final List<EqBand> eqBands;
  final Point3D? position;

  const ChannelSetting({
    required this.enabled,
    required this.customName,
    required this.delayMs,
    required this.eqBands,
    this.position,
  });

  @override
  int get hashCode =>
      enabled.hashCode ^
      customName.hashCode ^
      delayMs.hashCode ^
      eqBands.hashCode ^
      position.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChannelSetting &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          customName == other.customName &&
          delayMs == other.delayMs &&
          eqBands == other.eqBands &&
          position == other.position;
}

class EqBand {
  final bool enabled;
  final double freq;
  final double gain;
  final double qFactor;
  final EqType filterType;

  const EqBand({
    required this.enabled,
    required this.freq,
    required this.gain,
    required this.qFactor,
    required this.filterType,
  });

  @override
  int get hashCode =>
      enabled.hashCode ^
      freq.hashCode ^
      gain.hashCode ^
      qFactor.hashCode ^
      filterType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EqBand &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          freq == other.freq &&
          gain == other.gain &&
          qFactor == other.qFactor &&
          filterType == other.filterType;
}

enum EqType { lowCut, lowShelf, bell, notch, highShelf, highCut }

class Point3D {
  final double x;
  final double y;
  final double z;

  const Point3D({required this.x, required this.y, required this.z});

  @override
  int get hashCode => x.hashCode ^ y.hashCode ^ z.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Point3D &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          z == other.z;
}

class RoomConfig {
  final String id;
  final String name;
  final String colorHex;
  final double volume;
  final String clearOscAddress;
  final List<TrackConfig> tracks;

  const RoomConfig({
    required this.id,
    required this.name,
    required this.colorHex,
    required this.volume,
    required this.clearOscAddress,
    required this.tracks,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      colorHex.hashCode ^
      volume.hashCode ^
      clearOscAddress.hashCode ^
      tracks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomConfig &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          colorHex == other.colorHex &&
          volume == other.volume &&
          clearOscAddress == other.clearOscAddress &&
          tracks == other.tracks;
}

class RoomZone {
  final int roomId;
  final Point3D boundaryMin;
  final Point3D boundaryMax;
  final double boundaryDelayMs;
  final List<EqBand> boundaryEqBands;

  const RoomZone({
    required this.roomId,
    required this.boundaryMin,
    required this.boundaryMax,
    required this.boundaryDelayMs,
    required this.boundaryEqBands,
  });

  @override
  int get hashCode =>
      roomId.hashCode ^
      boundaryMin.hashCode ^
      boundaryMax.hashCode ^
      boundaryDelayMs.hashCode ^
      boundaryEqBands.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomZone &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          boundaryMin == other.boundaryMin &&
          boundaryMax == other.boundaryMax &&
          boundaryDelayMs == other.boundaryDelayMs &&
          boundaryEqBands == other.boundaryEqBands;
}

class TrackConfig {
  final String id;
  final String name;
  final String filePath;
  final double volume;
  final bool isLoop;
  final bool isStreaming;
  final int outputChannel;
  final bool outputStereo;
  final String playOscAddress;
  final String stopOscAddress;

  const TrackConfig({
    required this.id,
    required this.name,
    required this.filePath,
    required this.volume,
    required this.isLoop,
    required this.isStreaming,
    required this.outputChannel,
    required this.outputStereo,
    required this.playOscAddress,
    required this.stopOscAddress,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      filePath.hashCode ^
      volume.hashCode ^
      isLoop.hashCode ^
      isStreaming.hashCode ^
      outputChannel.hashCode ^
      outputStereo.hashCode ^
      playOscAddress.hashCode ^
      stopOscAddress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackConfig &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          filePath == other.filePath &&
          volume == other.volume &&
          isLoop == other.isLoop &&
          isStreaming == other.isStreaming &&
          outputChannel == other.outputChannel &&
          outputStereo == other.outputStereo &&
          playOscAddress == other.playOscAddress &&
          stopOscAddress == other.stopOscAddress;
}

class Trajectory {
  final List<Point3D> waypoints;
  final Point3D currentPosition;

  const Trajectory({required this.waypoints, required this.currentPosition});

  @override
  int get hashCode => waypoints.hashCode ^ currentPosition.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Trajectory &&
          runtimeType == other.runtimeType &&
          waypoints == other.waypoints &&
          currentPosition == other.currentPosition;
}
