import re

with open('lib/src/rust/frb_generated.dart', 'r') as f:
    content = f.read()

# Make sure all syntax is strictly correct for Riverpod
print("This file is auto-generated by flutter_rust_bridge. Run build runner.")
