// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class OscMetricsDto {
  final BigInt totalPackets;
  final BigInt totalBytes;
  final BigInt validMessages;
  final BigInt decodeErrors;
  final BigInt pps;
  final BigInt kbps;
  final String lastAddress;

  const OscMetricsDto({
    required this.totalPackets,
    required this.totalBytes,
    required this.validMessages,
    required this.decodeErrors,
    required this.pps,
    required this.kbps,
    required this.lastAddress,
  });

  @override
  int get hashCode =>
      totalPackets.hashCode ^
      totalBytes.hashCode ^
      validMessages.hashCode ^
      decodeErrors.hashCode ^
      pps.hashCode ^
      kbps.hashCode ^
      lastAddress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OscMetricsDto &&
          runtimeType == other.runtimeType &&
          totalPackets == other.totalPackets &&
          totalBytes == other.totalBytes &&
          validMessages == other.validMessages &&
          decodeErrors == other.decodeErrors &&
          pps == other.pps &&
          kbps == other.kbps &&
          lastAddress == other.lastAddress;
}
