// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/error.dart';
import 'api/simple.dart';
import 'common/config.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  Map<String, Point3D> dco_decode_Map_String_point_3_d_None(dynamic raw);

  @protected
  Map<int, ChannelSetting> dco_decode_Map_u_32_channel_setting_None(
    dynamic raw,
  );

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw);

  @protected
  RustStreamSink<EngineStateUpdate>
  dco_decode_StreamSink_engine_state_update_Sse(dynamic raw);

  @protected
  RustStreamSink<Float32List> dco_decode_StreamSink_list_prim_f_32_strict_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AppConfig dco_decode_app_config(dynamic raw);

  @protected
  AtmosError dco_decode_atmos_error(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AppConfig dco_decode_box_autoadd_app_config(dynamic raw);

  @protected
  Point3D dco_decode_box_autoadd_point_3_d(dynamic raw);

  @protected
  Trajectory dco_decode_box_autoadd_trajectory(dynamic raw);

  @protected
  ChannelSetting dco_decode_channel_setting(dynamic raw);

  @protected
  ChannelTuningParams dco_decode_channel_tuning_params(dynamic raw);

  @protected
  EngineStateUpdate dco_decode_engine_state_update(dynamic raw);

  @protected
  EqBand dco_decode_eq_band(dynamic raw);

  @protected
  EqType dco_decode_eq_type(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ChannelTuningParams> dco_decode_list_channel_tuning_params(dynamic raw);

  @protected
  List<EqBand> dco_decode_list_eq_band(dynamic raw);

  @protected
  List<Point3D?> dco_decode_list_opt_box_autoadd_point_3_d(dynamic raw);

  @protected
  List<OutputDeviceInfo> dco_decode_list_output_device_info(dynamic raw);

  @protected
  List<Point3D> dco_decode_list_point_3_d(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, Point3D)> dco_decode_list_record_string_point_3_d(dynamic raw);

  @protected
  List<(int, ChannelSetting)> dco_decode_list_record_u_32_channel_setting(
    dynamic raw,
  );

  @protected
  List<RoomConfig> dco_decode_list_room_config(dynamic raw);

  @protected
  List<RoomZone> dco_decode_list_room_zone(dynamic raw);

  @protected
  List<TrackConfig> dco_decode_list_track_config(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  Point3D? dco_decode_opt_box_autoadd_point_3_d(dynamic raw);

  @protected
  Trajectory? dco_decode_opt_box_autoadd_trajectory(dynamic raw);

  @protected
  OutputDeviceInfo dco_decode_output_device_info(dynamic raw);

  @protected
  Point3D dco_decode_point_3_d(dynamic raw);

  @protected
  (String, Point3D) dco_decode_record_string_point_3_d(dynamic raw);

  @protected
  (int, ChannelSetting) dco_decode_record_u_32_channel_setting(dynamic raw);

  @protected
  RoomConfig dco_decode_room_config(dynamic raw);

  @protected
  RoomZone dco_decode_room_zone(dynamic raw);

  @protected
  SpatialConfigPayload dco_decode_spatial_config_payload(dynamic raw);

  @protected
  TrackConfig dco_decode_track_config(dynamic raw);

  @protected
  Trajectory dco_decode_trajectory(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Map<String, Point3D> sse_decode_Map_String_point_3_d_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<int, ChannelSetting> sse_decode_Map_u_32_channel_setting_None(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<EngineStateUpdate>
  sse_decode_StreamSink_engine_state_update_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<Float32List> sse_decode_StreamSink_list_prim_f_32_strict_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AppConfig sse_decode_app_config(SseDeserializer deserializer);

  @protected
  AtmosError sse_decode_atmos_error(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AppConfig sse_decode_box_autoadd_app_config(SseDeserializer deserializer);

  @protected
  Point3D sse_decode_box_autoadd_point_3_d(SseDeserializer deserializer);

  @protected
  Trajectory sse_decode_box_autoadd_trajectory(SseDeserializer deserializer);

  @protected
  ChannelSetting sse_decode_channel_setting(SseDeserializer deserializer);

  @protected
  ChannelTuningParams sse_decode_channel_tuning_params(
    SseDeserializer deserializer,
  );

  @protected
  EngineStateUpdate sse_decode_engine_state_update(
    SseDeserializer deserializer,
  );

  @protected
  EqBand sse_decode_eq_band(SseDeserializer deserializer);

  @protected
  EqType sse_decode_eq_type(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ChannelTuningParams> sse_decode_list_channel_tuning_params(
    SseDeserializer deserializer,
  );

  @protected
  List<EqBand> sse_decode_list_eq_band(SseDeserializer deserializer);

  @protected
  List<Point3D?> sse_decode_list_opt_box_autoadd_point_3_d(
    SseDeserializer deserializer,
  );

  @protected
  List<OutputDeviceInfo> sse_decode_list_output_device_info(
    SseDeserializer deserializer,
  );

  @protected
  List<Point3D> sse_decode_list_point_3_d(SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, Point3D)> sse_decode_list_record_string_point_3_d(
    SseDeserializer deserializer,
  );

  @protected
  List<(int, ChannelSetting)> sse_decode_list_record_u_32_channel_setting(
    SseDeserializer deserializer,
  );

  @protected
  List<RoomConfig> sse_decode_list_room_config(SseDeserializer deserializer);

  @protected
  List<RoomZone> sse_decode_list_room_zone(SseDeserializer deserializer);

  @protected
  List<TrackConfig> sse_decode_list_track_config(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  Point3D? sse_decode_opt_box_autoadd_point_3_d(SseDeserializer deserializer);

  @protected
  Trajectory? sse_decode_opt_box_autoadd_trajectory(
    SseDeserializer deserializer,
  );

  @protected
  OutputDeviceInfo sse_decode_output_device_info(SseDeserializer deserializer);

  @protected
  Point3D sse_decode_point_3_d(SseDeserializer deserializer);

  @protected
  (String, Point3D) sse_decode_record_string_point_3_d(
    SseDeserializer deserializer,
  );

  @protected
  (int, ChannelSetting) sse_decode_record_u_32_channel_setting(
    SseDeserializer deserializer,
  );

  @protected
  RoomConfig sse_decode_room_config(SseDeserializer deserializer);

  @protected
  RoomZone sse_decode_room_zone(SseDeserializer deserializer);

  @protected
  SpatialConfigPayload sse_decode_spatial_config_payload(
    SseDeserializer deserializer,
  );

  @protected
  TrackConfig sse_decode_track_config(SseDeserializer deserializer);

  @protected
  Trajectory sse_decode_trajectory(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_point_3_d_None(
    Map<String, Point3D> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_u_32_channel_setting_None(
    Map<int, ChannelSetting> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_engine_state_update_Sse(
    RustStreamSink<EngineStateUpdate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_prim_f_32_strict_Sse(
    RustStreamSink<Float32List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_app_config(AppConfig self, SseSerializer serializer);

  @protected
  void sse_encode_atmos_error(AtmosError self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_app_config(
    AppConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_point_3_d(Point3D self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_trajectory(
    Trajectory self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_channel_setting(
    ChannelSetting self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_channel_tuning_params(
    ChannelTuningParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_engine_state_update(
    EngineStateUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_eq_band(EqBand self, SseSerializer serializer);

  @protected
  void sse_encode_eq_type(EqType self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_channel_tuning_params(
    List<ChannelTuningParams> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_eq_band(List<EqBand> self, SseSerializer serializer);

  @protected
  void sse_encode_list_opt_box_autoadd_point_3_d(
    List<Point3D?> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_output_device_info(
    List<OutputDeviceInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_point_3_d(List<Point3D> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_point_3_d(
    List<(String, Point3D)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_u_32_channel_setting(
    List<(int, ChannelSetting)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_room_config(
    List<RoomConfig> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_room_zone(List<RoomZone> self, SseSerializer serializer);

  @protected
  void sse_encode_list_track_config(
    List<TrackConfig> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_point_3_d(
    Point3D? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_trajectory(
    Trajectory? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_output_device_info(
    OutputDeviceInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_point_3_d(Point3D self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_point_3_d(
    (String, Point3D) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_32_channel_setting(
    (int, ChannelSetting) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_room_config(RoomConfig self, SseSerializer serializer);

  @protected
  void sse_encode_room_zone(RoomZone self, SseSerializer serializer);

  @protected
  void sse_encode_spatial_config_payload(
    SpatialConfigPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_track_config(TrackConfig self, SseSerializer serializer);

  @protected
  void sse_encode_trajectory(Trajectory self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
