// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../common/config.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// DBAP (Distance-Based Amplitude Panning) 기반 3D 음압 히트맵 연산
/// Inverse Square Law 롤오프를 사용하여 그리드 상의 각 포인트에 대한 총 음압을 0.0 ~ 1.0으로 정규화하여 반환합니다.
Float32List apiCalculateDbapHeatmap({
  required List<Point3D> speakers,
  required double roomWidth,
  required double roomDepth,
  required BigInt gridSize,
  required double rolloffFactor,
}) => RustLib.instance.api.crateApiAcousticsApiCalculateDbapHeatmap(
  speakers: speakers,
  roomWidth: roomWidth,
  roomDepth: roomDepth,
  gridSize: gridSize,
  rolloffFactor: rolloffFactor,
);

/// 새로운 스피커 생성 시 사용 중이지 않은 가장 빠른 채널 번호(1번부터 스캔)를 자동 할당하여 반환합니다.
int apiAllocateNextSpeakerChannel() =>
    RustLib.instance.api.crateApiAcousticsApiAllocateNextSpeakerChannel();

/// 글로벌 리버브 믹스(Reverb Mix) 및 감쇠 시간(Reverb Decay)을 설정합니다.
void apiSetGlobalReverb({required double mix, required double decay}) => RustLib
    .instance
    .api
    .crateApiAcousticsApiSetGlobalReverb(mix: mix, decay: decay);

/// 특정 룸 존의 차음 성능(Transmission Loss, dB)을 설정합니다.
void apiSetTransmissionLoss({
  required int roomZoneId,
  required double lossDb,
}) => RustLib.instance.api.crateApiAcousticsApiSetTransmissionLoss(
  roomZoneId: roomZoneId,
  lossDb: lossDb,
);
