// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../common/config.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<List<CalibrationResult>> calculate3DCalibration({
  required double roomWidth,
  required double roomDepth,
  required double earLevel,
  required List<(BigInt, Point3D)> speakers,
}) => RustLib.instance.api.crateApiCalibrationCalculate3DCalibration(
  roomWidth: roomWidth,
  roomDepth: roomDepth,
  earLevel: earLevel,
  speakers: speakers,
);

class CalibrationResult {
  final BigInt channel;
  final double delayMs;
  final double gainDb;

  const CalibrationResult({
    required this.channel,
    required this.delayMs,
    required this.gainDb,
  });

  static Future<CalibrationResult> default_() =>
      RustLib.instance.api.crateApiCalibrationCalibrationResultDefault();

  @override
  int get hashCode => channel.hashCode ^ delayMs.hashCode ^ gainDb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CalibrationResult &&
          runtimeType == other.runtimeType &&
          channel == other.channel &&
          delayMs == other.delayMs &&
          gainDb == other.gainDb;
}
