// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bring_window_to_front`, `launch_supervisor`, `supervisor_next_to_app`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

/// 창을 띄우기 전에 한 번 부른다. [args]는 앱 실행 인자다.
Future<StartupDecision> apiStartupGate({required List<String> args}) =>
    RustLib.instance.api.crateApiLifecycleApiStartupGate(args: args);

/// Dart가 2초마다 부른다. 감시가 이 파일로 앱이 응답하는지 본다.
Future<void> apiHeartbeat() =>
    RustLib.instance.api.crateApiLifecycleApiHeartbeat();

/// 운영자가 창을 닫을 때 엔진을 멈추기 전에 부른다. 감시는 이 앱을 다시 띄우지 않는다.
Future<void> apiMarkCleanExit() =>
    RustLib.instance.api.crateApiLifecycleApiMarkCleanExit();

/// 시작 관문의 결정. Dart `main`이 창을 띄우기 전에 받아 그대로 한다.
enum StartupDecision {
  /// 계속 시작한다.
  proceed,

  /// 감시 프로그램을 띄웠다. 앱은 종료 코드 0으로 끝낸다(감시가 앱을 다시 띄운다).
  handedToSupervisor,

  /// 다른 앱이 이미 떠 있다(그 창을 앞으로 가져왔다). 종료 코드 3으로 끝낸다.
  duplicate,
}
