// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `handle_osc_packet`

Future<bool> validateOscPacket({
  required SocketAddr senderAddr,
  required List<IpAddr> whitelist,
  required List<int> rawBytes,
}) => RustLib.instance.api.crateApiOscValidateOscPacket(
  senderAddr: senderAddr,
  whitelist: whitelist,
  rawBytes: rawBytes,
);

Future<UdpSocket> createHighCapacityOscSocket({required int port}) =>
    RustLib.instance.api.crateApiOscCreateHighCapacityOscSocket(port: port);

Future<void> startOscServer() =>
    RustLib.instance.api.crateApiOscStartOscServer();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< IpAddr>>
abstract class IpAddr implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SocketAddr>>
abstract class SocketAddr implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< UdpSocket>>
abstract class UdpSocket implements RustOpaqueInterface {}
