// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../common/config.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 트랙 오디오 경로를 [search_dirs](앞의 것 먼저)와 그 하위 폴더에서 파일 이름으로 다시 연결한다.
/// 저장된 경로에 파일이 있으면 그대로 둔다. 엔진 설정의 다른 값은 건드리지 않는다.
Future<RelinkedConfig> apiRelinkTrackPaths({
  required AppConfig config,
  required List<String> searchDirs,
}) => RustLib.instance.api.crateApiProjectApiRelinkTrackPaths(
  config: config,
  searchDirs: searchDirs,
);

/// 파일 하나(도면 이미지)를 같은 방법으로 찾는다. 저장된 경로에 있으면 그 경로, 못 찾으면 None.
Future<String?> apiFindMedia({
  required String path,
  required List<String> searchDirs,
}) => RustLib.instance.api.crateApiProjectApiFindMedia(
  path: path,
  searchDirs: searchDirs,
);

/// 다시 연결한 엔진 설정과 끝까지 못 찾은 파일.
class RelinkedConfig {
  final AppConfig config;

  /// 못 찾은 파일의 원래 경로(같은 경로는 한 번만).
  final List<String> missing;

  const RelinkedConfig({required this.config, required this.missing});

  @override
  int get hashCode => config.hashCode ^ missing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RelinkedConfig &&
          runtimeType == other.runtimeType &&
          config == other.config &&
          missing == other.missing;
}
