// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../common/config.dart';
import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Load Project 전에 부른다. 프로젝트 파일을 앱 설정과 같은 규칙으로 해석해 보기만 하고 상태는 바꾸지 않는다.
/// 읽을 수 없거나 Atmos 프로젝트가 아니면 이유를 돌려준다. `api_get_config`는 앱 자신의 config.json용이라 읽기에
/// 실패하면 기본 설정을 돌려주고 엔진 설정·채널 튜닝까지 바꿔, 잘못 고른 파일로 지금 설정이 비워졌다
/// (2026-10-10 Windows). 없는 파일을 기본 설정으로 만들거나 깨진 파일의 사본을 남기지도 않는다.
Future<void> apiCheckProjectFile({required String path}) =>
    RustLib.instance.api.crateApiProjectApiCheckProjectFile(path: path);

/// File > Export Project가 부른다. 프로젝트 파일만 쓰고 엔진의 지금 설정·채널 상태는 바꾸지 않는다.
/// `api_save_config`는 파일을 쓰면서 엔진 설정까지 넘겨받은 설정으로 바꾼다. 내보낼 설정은 트랙·도면 경로가
/// 복사본을 가리키므로, 그것으로 쓰면 지금 프로젝트까지 복사본을 가리키게 됐다(2026-10-10 Mac 확인). 폴더가 없으면
/// 만들고, 쓰기는 앱 설정과 같은 원자적 쓰기다(`AppConfig::save_to_file`).
Future<void> apiWriteProjectFile({
  required String path,
  required AppConfig config,
}) => RustLib.instance.api.crateApiProjectApiWriteProjectFile(
  path: path,
  config: config,
);

/// 트랙 오디오 경로를 [search_dirs](앞의 것 먼저)와 그 하위 폴더에서 파일 이름으로 다시 연결한다.
/// 저장된 경로에 파일이 있으면 그대로 둔다. 엔진 설정의 다른 값은 건드리지 않는다.
Future<RelinkedConfig> apiRelinkTrackPaths({
  required AppConfig config,
  required List<String> searchDirs,
}) => RustLib.instance.api.crateApiProjectApiRelinkTrackPaths(
  config: config,
  searchDirs: searchDirs,
);

/// 파일 하나(도면 이미지)를 같은 방법으로 찾는다. 저장된 경로에 있으면 그 경로, 못 찾으면 None.
Future<String?> apiFindMedia({
  required String path,
  required List<String> searchDirs,
}) => RustLib.instance.api.crateApiProjectApiFindMedia(
  path: path,
  searchDirs: searchDirs,
);

/// 다시 연결한 엔진 설정과 끝까지 못 찾은 파일.
class RelinkedConfig {
  final AppConfig config;

  /// 못 찾은 파일의 원래 경로(같은 경로는 한 번만).
  final List<String> missing;

  const RelinkedConfig({required this.config, required this.missing});

  @override
  int get hashCode => config.hashCode ^ missing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RelinkedConfig &&
          runtimeType == other.runtimeType &&
          config == other.config &&
          missing == other.missing;
}
