// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> saveScene({required String sceneId, required String name}) =>
    RustLib.instance.api.crateApiSceneSaveScene(sceneId: sceneId, name: name);

Future<void> loadScene({required String sceneId}) =>
    RustLib.instance.api.crateApiSceneLoadScene(sceneId: sceneId);

Future<void> clearRoom() => RustLib.instance.api.crateApiSceneClearRoom();
