// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 지난 공연 상태를 읽어 두고 5초마다 저장을 시작한다. 앱 시작 때(시작 관문 다음) 한 번 부른다.
/// [dir]는 앱 지원 폴더(설정 파일과 같은 곳)다.
Future<void> apiStartShowState({required String dir}) =>
    RustLib.instance.api.crateApiShowApiStartShowState(dir: dir);

/// 감시가 다시 띄웠거나(--auto-relaunched) 로그인 자동 실행이면, 앱 시작 절차(설정 적용·엔진 준비) 뒤 한 번 부른다.
/// 시작할 때 읽어 둔 위치부터 이어 가고, 이어 갈 수 없으면 첫 방 테마로 시작한다.
Future<void> apiResumeShow() =>
    RustLib.instance.api.crateApiShowApiResumeShow();

/// 첫 방 테마 시작: 전체 정지 → 설정의 첫 방을 활성으로 → 그 방 루프 재생. OSC 테마 시작과 같다.
Future<void> apiThemeStart() =>
    RustLib.instance.api.crateApiShowApiThemeStart();
