// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../common/config.dart';
import '../frb_generated.dart';
import '../osc/metrics.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_enabled_channels`, `init_audio_system`, `monitored_output_device_names`, `play_track_from`, `request_restart_if_processing_width_changed`, `sim_band_from_json`, `start_audio_system`, `stop_audio_engine`, `with_start`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ENGINE_ACTIVE`, `ENGINE_THREAD`, `STREAM_STATUS_SINK`, `VU_THREAD_RUNNING`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `deref`, `deref`, `deref`, `deref`, `fmt`, `fmt`, `fmt`, `initialize`, `initialize`, `initialize`, `initialize`
// These functions have error during generation (see debug logs or enable `stop_on_error: true` for more details): `build_play_track_command`

Future<void> apiUpdateSingleBandEq({
  required BigInt channelIndex,
  required BigInt bandIndex,
  required double frequency,
  required double gainDb,
  required double qFactor,
  required int filterTypeIdx,
}) => RustLib.instance.api.crateApiSimpleApiUpdateSingleBandEq(
  channelIndex: channelIndex,
  bandIndex: bandIndex,
  frequency: frequency,
  gainDb: gainDb,
  qFactor: qFactor,
  filterTypeIdx: filterTypeIdx,
);

Future<void> apiUpdateSoundSourcePosition({
  required String soundId,
  required double x,
  required double y,
  required double z,
}) => RustLib.instance.api.crateApiSimpleApiUpdateSoundSourcePosition(
  soundId: soundId,
  x: x,
  y: y,
  z: z,
);

/// Output Config(`mono_configs`/`stereo_configs`/`multi_configs`)로부터 믹서 출력 게이트
/// (`GLOBAL_STATE.enabled_channels`)에 쓸 0-based 활성화 벡터를 계산하는 순수 함수.
///
/// ## 0/1-based 규약 (OUTPUT_CHANNEL_MAPPING_UNIFICATION_SPEC.md 3절)
/// `config.json`의 세 맵은 키가 **1-based**(사용자에게 보이는 채널 번호)이고,
/// 반환하는 `Vec<bool>`과 `GLOBAL_STATE.enabled_channels`는 **0-based**(CPAL `hw_ch` 인덱스)이다.
/// 이 변환(`ch as usize - 1`)은 이 함수 안에서만 일어난다 — 호출부에서 다시 변환하지 말 것.
///
/// ## 그룹별 채널 개방 규칙
/// - Mono: `ch-1`, `ch`(1-based 페어) 두 채널을 연다 — 기존 "모노 1개가 L/R 페어를 연다" 설계 유지.
/// - Stereo: 위와 동일한 페어 개방(기존 동작 유지, 이번 수정 범위 아님).
/// - Multi: 시작 채널(`ch-1`, 0-based)부터 하드웨어 마지막 채널까지 전체 구간을 연다.
///   `ChannelSetting`에는 그룹이 몇 채널짜리인지(N) 저장되지 않고, 실제로 몇 채널을 쓸지는
///   재생되는 파일의 채널 수에 따라 트랙별 라우팅(믹서 쓰기 단계)에서 결정되므로, 이 게이트는
///   "시작 채널 이후로는 무엇이 와도 막지 않는다"는 상한만 담당한다(SPEC 3.1절).
///
/// 세 맵이 모두 비어 있으면(사용자가 Output Config를 아직 건드리지 않음) 하위호환을 위해
/// 전 채널을 개방한다.
Future<List<bool>> computeEnabledChannels({
  required AppConfig config,
  required BigInt hwLen,
}) => RustLib.instance.api.crateApiSimpleComputeEnabledChannels(
  config: config,
  hwLen: hwLen,
);

Future<AppConfig> apiGetConfig({required String path}) =>
    RustLib.instance.api.crateApiSimpleApiGetConfig(path: path);

Future<void> apiSaveConfig({required String path, required AppConfig config}) =>
    RustLib.instance.api.crateApiSimpleApiSaveConfig(
      path: path,
      config: config,
    );

Future<void> apiPreloadSound({required String filePath}) =>
    RustLib.instance.api.crateApiSimpleApiPreloadSound(filePath: filePath);

Future<void> apiClearPreloadedSounds() =>
    RustLib.instance.api.crateApiSimpleApiClearPreloadedSounds();

Future<Float32List> apiGetRtaMagnitudes() =>
    RustLib.instance.api.crateApiSimpleApiGetRtaMagnitudes();

Future<Float32List> apiGetSpatialGains() =>
    RustLib.instance.api.crateApiSimpleApiGetSpatialGains();

Future<Float32List> apiCalculateEqResponse({required List<EqBand> bands}) =>
    RustLib.instance.api.crateApiSimpleApiCalculateEqResponse(bands: bands);

Future<void> apiPlayTrack({required String roomId, required String trackId}) =>
    RustLib.instance.api.crateApiSimpleApiPlayTrack(
      roomId: roomId,
      trackId: trackId,
    );

Future<void> apiStopTrack({required String roomId, required String trackId}) =>
    RustLib.instance.api.crateApiSimpleApiStopTrack(
      roomId: roomId,
      trackId: trackId,
    );

Future<void> apiStopAll() => RustLib.instance.api.crateApiSimpleApiStopAll();

Future<void> apiSetActiveRoom({String? roomId}) =>
    RustLib.instance.api.crateApiSimpleApiSetActiveRoom(roomId: roomId);

Future<void> apiClearRoom({required String roomId}) =>
    RustLib.instance.api.crateApiSimpleApiClearRoom(roomId: roomId);

Future<void> apiSetMasterMute({required bool muted}) =>
    RustLib.instance.api.crateApiSimpleApiSetMasterMute(muted: muted);

Future<void> apiSetMasterVolume({
  required String roomId,
  required double volume,
}) => RustLib.instance.api.crateApiSimpleApiSetMasterVolume(
  roomId: roomId,
  volume: volume,
);

void apiSetTrackVolume({
  required String roomId,
  required String trackId,
  required double volume,
}) => RustLib.instance.api.crateApiSimpleApiSetTrackVolume(
  roomId: roomId,
  trackId: trackId,
  volume: volume,
);

Future<void> apiSetTrackOutput({
  required String roomId,
  required String trackId,
  required BigInt outputChannel,
  required bool outputStereo,
}) => RustLib.instance.api.crateApiSimpleApiSetTrackOutput(
  roomId: roomId,
  trackId: trackId,
  outputChannel: outputChannel,
  outputStereo: outputStereo,
);

Future<void> apiSetChannelDelay({
  required BigInt channel,
  required double delayMs,
}) => RustLib.instance.api.crateApiSimpleApiSetChannelDelay(
  channel: channel,
  delayMs: delayMs,
);

Future<void> apiSetChannelEq({
  required BigInt channel,
  required List<EqBand> bands,
}) => RustLib.instance.api.crateApiSimpleApiSetChannelEq(
  channel: channel,
  bands: bands,
);

Stream<Float32List> apiCreateVuStream() =>
    RustLib.instance.api.crateApiSimpleApiCreateVuStream();

Future<void> broadcastStreamStatus({required String status}) =>
    RustLib.instance.api.crateApiSimpleBroadcastStreamStatus(status: status);

Stream<String> apiCreateStreamStatusStream() =>
    RustLib.instance.api.crateApiSimpleApiCreateStreamStatusStream();

Future<void> apiInitAudioSystem({String? deviceName}) => RustLib.instance.api
    .crateApiSimpleApiInitAudioSystem(deviceName: deviceName);

Future<void> apiStartAudioEngine({String? deviceName}) => RustLib.instance.api
    .crateApiSimpleApiStartAudioEngine(deviceName: deviceName);

/// 재생 중인 트랙별 재생 위치(초). 오디오 스레드가 원자 칸에 적어 둔 값을 읽기만 한다.
Future<List<PlaybackPosition>> apiGetPlaybackPositions() =>
    RustLib.instance.api.crateApiSimpleApiGetPlaybackPositions();

/// Dart가 `seq`번 엔진 재시작 뒤 재동기화를 마쳤다고 알린다(core::restart_resume).
Future<void> apiAckEngineRestart({required int seq}) =>
    RustLib.instance.api.crateApiSimpleApiAckEngineRestart(seq: seq);

Future<bool> apiIsEngineReady() =>
    RustLib.instance.api.crateApiSimpleApiIsEngineReady();

Future<void> apiStopAudioEngine() =>
    RustLib.instance.api.crateApiSimpleApiStopAudioEngine();

Future<void> apiOpenAsioPanel() =>
    RustLib.instance.api.crateApiSimpleApiOpenAsioPanel();

Future<void> apiGetAsioPanel() =>
    RustLib.instance.api.crateApiSimpleApiGetAsioPanel();

Stream<String> apiCreateDeviceEventStream() =>
    RustLib.instance.api.crateApiSimpleApiCreateDeviceEventStream();

Future<void> apiForceRestartEngine({String? deviceName}) => RustLib.instance.api
    .crateApiSimpleApiForceRestartEngine(deviceName: deviceName);

Future<void> apiStartOscListener({required int port}) =>
    RustLib.instance.api.crateApiSimpleApiStartOscListener(port: port);

Stream<EngineStateUpdate> apiCreateEngineStateStream() =>
    RustLib.instance.api.crateApiSimpleApiCreateEngineStateStream();

Future<void> apiPreloadAllSounds({required AppConfig config}) =>
    RustLib.instance.api.crateApiSimpleApiPreloadAllSounds(config: config);

Future<List<OutputDeviceInfo>> apiGetOutputDevices() =>
    RustLib.instance.api.crateApiSimpleApiGetOutputDevices();

Future<int> apiGetDeviceChannelCount({String? deviceName}) => RustLib
    .instance
    .api
    .crateApiSimpleApiGetDeviceChannelCount(deviceName: deviceName);

Future<List<String>> apiGetDeviceChannelNames({String? deviceName}) => RustLib
    .instance
    .api
    .crateApiSimpleApiGetDeviceChannelNames(deviceName: deviceName);

Future<void> apiExportLogs({required String destinationDir}) => RustLib
    .instance
    .api
    .crateApiSimpleApiExportLogs(destinationDir: destinationDir);

Future<void> apiPlayAllLoopTracks() =>
    RustLib.instance.api.crateApiSimpleApiPlayAllLoopTracks();

Future<void> apiLoadPreset({required AppConfig config}) =>
    RustLib.instance.api.crateApiSimpleApiLoadPreset(config: config);

Future<void> apiTriggerTestError({required String message}) =>
    RustLib.instance.api.crateApiSimpleApiTriggerTestError(message: message);

Future<int> apiGetAudioFileChannels({required String filePath}) => RustLib
    .instance
    .api
    .crateApiSimpleApiGetAudioFileChannels(filePath: filePath);

Future<void> apiApplyAllChannelTunings({
  required List<ChannelTuningParams> tunings,
}) => RustLib.instance.api.crateApiSimpleApiApplyAllChannelTunings(
  tunings: tunings,
);

Future<void> apiApplyChannelTuning({
  required int channel,
  required double delayMs,
  required List<EqBand> eqBands,
  required bool phaseInvert,
  required double gainDb,
}) => RustLib.instance.api.crateApiSimpleApiApplyChannelTuning(
  channel: channel,
  delayMs: delayMs,
  eqBands: eqBands,
  phaseInvert: phaseInvert,
  gainDb: gainDb,
);

Future<void> apiApplyGlobalTuning({
  required double masterHeadroomDb,
  required bool peakLimiterEnabled,
}) => RustLib.instance.api.crateApiSimpleApiApplyGlobalTuning(
  masterHeadroomDb: masterHeadroomDb,
  peakLimiterEnabled: peakLimiterEnabled,
);

Future<void> apiUpdateSpatialConfigJson({required String jsonPayload}) =>
    RustLib.instance.api.crateApiSimpleApiUpdateSpatialConfigJson(
      jsonPayload: jsonPayload,
    );

void apiSetChannelPanDeg({required BigInt channel, required double panDeg}) =>
    RustLib.instance.api.crateApiSimpleApiSetChannelPanDeg(
      channel: channel,
      panDeg: panDeg,
    );

void apiSetChannelEarlyRefMix({required BigInt channel, required double mix}) =>
    RustLib.instance.api.crateApiSimpleApiSetChannelEarlyRefMix(
      channel: channel,
      mix: mix,
    );

Future<Point3D> apiCalculateBezierPoint({
  required double t,
  required Point3D p0,
  required Point3D p1,
  required Point3D p2,
  required Point3D p3,
}) => RustLib.instance.api.crateApiSimpleApiCalculateBezierPoint(
  t: t,
  p0: p0,
  p1: p1,
  p2: p2,
  p3: p3,
);

Future<Float32List> apiCalculateDbapHeatmap({
  required Point3D listenerPos,
  required List<Point3D> channelPositions,
}) => RustLib.instance.api.crateApiSimpleApiCalculateDbapHeatmap(
  listenerPos: listenerPos,
  channelPositions: channelPositions,
);

Float32List apiCalculateEqResponseCurve({
  required List<EqBand> bands,
  required BigInt numPoints,
  required double sampleRate,
}) => RustLib.instance.api.crateApiSimpleApiCalculateEqResponseCurve(
  bands: bands,
  numPoints: numPoints,
  sampleRate: sampleRate,
);

Future<List<String>> apiGetActiveOutputChannels({String? deviceName}) => RustLib
    .instance
    .api
    .crateApiSimpleApiGetActiveOutputChannels(deviceName: deviceName);

Future<OscMetricsDto> apiGetOscMetrics() =>
    RustLib.instance.api.crateApiSimpleApiGetOscMetrics();

Future<void> apiResetOscMetrics() =>
    RustLib.instance.api.crateApiSimpleApiResetOscMetrics();

void apiSetBinauralEnabled({required bool enabled}) =>
    RustLib.instance.api.crateApiSimpleApiSetBinauralEnabled(enabled: enabled);

void apiSetReverbParams({required double mix, required double decay}) => RustLib
    .instance
    .api
    .crateApiSimpleApiSetReverbParams(mix: mix, decay: decay);

void apiSetChannelReverbSend({required BigInt channel, required double send}) =>
    RustLib.instance.api.crateApiSimpleApiSetChannelReverbSend(
      channel: channel,
      send: send,
    );

void apiSetSpatialReverb({
  required bool isEnabled,
  required double roomSize,
  required double decayTime,
  required double preDelayMs,
  required double damp,
  required double density,
  required double dryWet,
}) => RustLib.instance.api.crateApiSimpleApiSetSpatialReverb(
  isEnabled: isEnabled,
  roomSize: roomSize,
  decayTime: decayTime,
  preDelayMs: preDelayMs,
  damp: damp,
  density: density,
  dryWet: dryWet,
);

void apiSetChannelSpatialReverb({
  required BigInt channel,
  required bool isEnabled,
  required double roomSize,
  required double decayTime,
  required double preDelayMs,
  required double damp,
  required double density,
  required double dryWet,
}) => RustLib.instance.api.crateApiSimpleApiSetChannelSpatialReverb(
  channel: channel,
  isEnabled: isEnabled,
  roomSize: roomSize,
  decayTime: decayTime,
  preDelayMs: preDelayMs,
  damp: damp,
  density: density,
  dryWet: dryWet,
);

/// LFE +10dB 토글(베이스 매니지먼트 패널). 서브 채널 자기 신호(.1 LFE 트랙)를 120Hz
/// 로우패스 **이후**에 +10dB 올린다. 메인에서 넘어온 저역에는 걸지 않는다.
/// 서브 레벨은 원래 최종 출력단이나 하드웨어에서 맞추고, 이건 바이노럴 미리듣기나
/// 소프트웨어로 맞춰야 할 때 쓴다.
void apiSetLfeBoostEnabled({required bool enabled}) =>
    RustLib.instance.api.crateApiSimpleApiSetLfeBoostEnabled(enabled: enabled);

/// 베이스 매니지먼트 크로스오버 주파수(모든 방 공통). 서브우퍼 지정은 방별이라
/// 스피커 속성으로 공간 설정 payload에 실려 온다(api_update_spatial_config_json).
void apiSetCrossoverFrequency({required double freq}) =>
    RustLib.instance.api.crateApiSimpleApiSetCrossoverFrequency(freq: freq);

class ChannelTuningParams {
  final int channel;
  final double delayMs;
  final List<EqBand> eqBands;
  final bool phaseInvert;
  final double gainDb;

  const ChannelTuningParams({
    required this.channel,
    required this.delayMs,
    required this.eqBands,
    required this.phaseInvert,
    required this.gainDb,
  });

  @override
  int get hashCode =>
      channel.hashCode ^
      delayMs.hashCode ^
      eqBands.hashCode ^
      phaseInvert.hashCode ^
      gainDb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChannelTuningParams &&
          runtimeType == other.runtimeType &&
          channel == other.channel &&
          delayMs == other.delayMs &&
          eqBands == other.eqBands &&
          phaseInvert == other.phaseInvert &&
          gainDb == other.gainDb;
}

class EngineStateUpdate {
  final String? activeRoomId;
  final bool duckingActive;
  final List<String> playingTrackIds;
  final String? engineError;
  final int outputChannelCount;
  final double shortTermLufs;
  final double gainReductionDb;

  const EngineStateUpdate({
    this.activeRoomId,
    required this.duckingActive,
    required this.playingTrackIds,
    this.engineError,
    required this.outputChannelCount,
    required this.shortTermLufs,
    required this.gainReductionDb,
  });

  @override
  int get hashCode =>
      activeRoomId.hashCode ^
      duckingActive.hashCode ^
      playingTrackIds.hashCode ^
      engineError.hashCode ^
      outputChannelCount.hashCode ^
      shortTermLufs.hashCode ^
      gainReductionDb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineStateUpdate &&
          runtimeType == other.runtimeType &&
          activeRoomId == other.activeRoomId &&
          duckingActive == other.duckingActive &&
          playingTrackIds == other.playingTrackIds &&
          engineError == other.engineError &&
          outputChannelCount == other.outputChannelCount &&
          shortTermLufs == other.shortTermLufs &&
          gainReductionDb == other.gainReductionDb;
}

class OutputDeviceInfo {
  final String name;
  final int maxChannels;
  final List<String> channelNames;

  const OutputDeviceInfo({
    required this.name,
    required this.maxChannels,
    required this.channelNames,
  });

  @override
  int get hashCode =>
      name.hashCode ^ maxChannels.hashCode ^ channelNames.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OutputDeviceInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          maxChannels == other.maxChannels &&
          channelNames == other.channelNames;
}

/// 재생 중인 트랙의 파일 기준 재생 위치. 루프는 한 바퀴 안의 위치다.
class PlaybackPosition {
  final String trackId;
  final double seconds;

  const PlaybackPosition({required this.trackId, required this.seconds});

  @override
  int get hashCode => trackId.hashCode ^ seconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaybackPosition &&
          runtimeType == other.runtimeType &&
          trackId == other.trackId &&
          seconds == other.seconds;
}

class SpatialConfigPayload {
  final List<Point3D?> channelPositions;
  final List<RoomZone> roomZones;
  final Trajectory? trajectory;
  final Map<String, Point3D> trackPositions;

  const SpatialConfigPayload({
    required this.channelPositions,
    required this.roomZones,
    this.trajectory,
    required this.trackPositions,
  });

  static Future<SpatialConfigPayload> default_() =>
      RustLib.instance.api.crateApiSimpleSpatialConfigPayloadDefault();

  @override
  int get hashCode =>
      channelPositions.hashCode ^
      roomZones.hashCode ^
      trajectory.hashCode ^
      trackPositions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpatialConfigPayload &&
          runtimeType == other.runtimeType &&
          channelPositions == other.channelPositions &&
          roomZones == other.roomZones &&
          trajectory == other.trajectory &&
          trackPositions == other.trackPositions;
}
