// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../common/config.dart';
import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ENGINE_ACTIVE`, `ENGINE_GENERATION`, `ENGINE_THREAD`, `SpatialConfigPayload`, `VU_THREAD_RUNNING`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `deref`, `deref`, `deref`, `deref`, `fmt`, `fmt`, `initialize`, `initialize`, `initialize`, `initialize`

Future<void> apiUpdateSingleBandEq({
  required BigInt channelIndex,
  required BigInt bandIndex,
  required double frequency,
  required double gainDb,
  required double qFactor,
  required int filterTypeIdx,
}) => RustLib.instance.api.crateApiSimpleApiUpdateSingleBandEq(
  channelIndex: channelIndex,
  bandIndex: bandIndex,
  frequency: frequency,
  gainDb: gainDb,
  qFactor: qFactor,
  filterTypeIdx: filterTypeIdx,
);

Future<void> apiUpdateSoundSourcePosition({
  required String soundId,
  required double x,
  required double y,
  required double z,
}) => RustLib.instance.api.crateApiSimpleApiUpdateSoundSourcePosition(
  soundId: soundId,
  x: x,
  y: y,
  z: z,
);

Future<AppConfig> apiGetConfig({required String path}) =>
    RustLib.instance.api.crateApiSimpleApiGetConfig(path: path);

Future<void> apiSaveConfig({required String path, required AppConfig config}) =>
    RustLib.instance.api.crateApiSimpleApiSaveConfig(
      path: path,
      config: config,
    );

Future<void> apiPlayTestNoise({required int channel}) =>
    RustLib.instance.api.crateApiSimpleApiPlayTestNoise(channel: channel);

Future<void> apiPreloadSound({required String filePath}) =>
    RustLib.instance.api.crateApiSimpleApiPreloadSound(filePath: filePath);

Future<void> apiClearPreloadedSounds() =>
    RustLib.instance.api.crateApiSimpleApiClearPreloadedSounds();

Future<Float32List> apiGetRtaMagnitudes() =>
    RustLib.instance.api.crateApiSimpleApiGetRtaMagnitudes();

Future<Float32List> apiGetSpatialGains() =>
    RustLib.instance.api.crateApiSimpleApiGetSpatialGains();

Future<Float32List> apiCalculateEqResponse({required List<EqBand> bands}) =>
    RustLib.instance.api.crateApiSimpleApiCalculateEqResponse(bands: bands);

Future<void> apiPlayTrack({required String roomId, required String trackId}) =>
    RustLib.instance.api.crateApiSimpleApiPlayTrack(
      roomId: roomId,
      trackId: trackId,
    );

Future<void> apiStopTrack({required String roomId, required String trackId}) =>
    RustLib.instance.api.crateApiSimpleApiStopTrack(
      roomId: roomId,
      trackId: trackId,
    );

Future<void> apiStopAll() => RustLib.instance.api.crateApiSimpleApiStopAll();

Future<void> apiSetActiveRoom({String? roomId}) =>
    RustLib.instance.api.crateApiSimpleApiSetActiveRoom(roomId: roomId);

Future<void> apiClearRoom({required String roomId}) =>
    RustLib.instance.api.crateApiSimpleApiClearRoom(roomId: roomId);

Future<void> apiSetMasterMute({required bool muted}) =>
    RustLib.instance.api.crateApiSimpleApiSetMasterMute(muted: muted);

Future<void> apiSetMasterVolume({
  required String roomId,
  required double volume,
}) => RustLib.instance.api.crateApiSimpleApiSetMasterVolume(
  roomId: roomId,
  volume: volume,
);

void apiSetTrackVolume({
  required String roomId,
  required String trackId,
  required double volume,
}) => RustLib.instance.api.crateApiSimpleApiSetTrackVolume(
  roomId: roomId,
  trackId: trackId,
  volume: volume,
);

Future<void> apiSetTrackOutput({
  required String roomId,
  required String trackId,
  required BigInt outputChannel,
  required bool outputStereo,
}) => RustLib.instance.api.crateApiSimpleApiSetTrackOutput(
  roomId: roomId,
  trackId: trackId,
  outputChannel: outputChannel,
  outputStereo: outputStereo,
);

Future<void> apiSetChannelDelay({
  required BigInt channel,
  required double delayMs,
}) => RustLib.instance.api.crateApiSimpleApiSetChannelDelay(
  channel: channel,
  delayMs: delayMs,
);

Future<void> apiSetChannelEq({
  required BigInt channel,
  required List<EqBand> bands,
}) => RustLib.instance.api.crateApiSimpleApiSetChannelEq(
  channel: channel,
  bands: bands,
);

Stream<Float32List> apiCreateVuStream() =>
    RustLib.instance.api.crateApiSimpleApiCreateVuStream();

Future<void> apiInitAudioSystem({String? deviceName}) => RustLib.instance.api
    .crateApiSimpleApiInitAudioSystem(deviceName: deviceName);

Future<void> apiStartAudioEngine({String? deviceName}) => RustLib.instance.api
    .crateApiSimpleApiStartAudioEngine(deviceName: deviceName);

Future<bool> apiIsEngineReady() =>
    RustLib.instance.api.crateApiSimpleApiIsEngineReady();

Future<void> apiStopAudioEngine() =>
    RustLib.instance.api.crateApiSimpleApiStopAudioEngine();

Future<void> apiOpenAsioPanel() =>
    RustLib.instance.api.crateApiSimpleApiOpenAsioPanel();

Stream<String> apiCreateDeviceEventStream() =>
    RustLib.instance.api.crateApiSimpleApiCreateDeviceEventStream();

Future<void> apiForceRestartEngine({String? deviceName}) => RustLib.instance.api
    .crateApiSimpleApiForceRestartEngine(deviceName: deviceName);

Future<void> apiStartOscListener({required int port}) =>
    RustLib.instance.api.crateApiSimpleApiStartOscListener(port: port);

Stream<EngineStateUpdate> apiCreateEngineStateStream() =>
    RustLib.instance.api.crateApiSimpleApiCreateEngineStateStream();

Future<void> apiPreloadAllSounds({required AppConfig config}) =>
    RustLib.instance.api.crateApiSimpleApiPreloadAllSounds(config: config);

Future<List<OutputDeviceInfo>> apiGetOutputDevices() =>
    RustLib.instance.api.crateApiSimpleApiGetOutputDevices();

Future<int> apiGetDeviceChannelCount({String? deviceName}) => RustLib
    .instance
    .api
    .crateApiSimpleApiGetDeviceChannelCount(deviceName: deviceName);

Future<List<String>> apiGetDeviceChannelNames({String? deviceName}) => RustLib
    .instance
    .api
    .crateApiSimpleApiGetDeviceChannelNames(deviceName: deviceName);

Future<void> apiExportLogs({required String destinationDir}) => RustLib
    .instance
    .api
    .crateApiSimpleApiExportLogs(destinationDir: destinationDir);

Future<void> apiPlayAllLoopTracks() =>
    RustLib.instance.api.crateApiSimpleApiPlayAllLoopTracks();

Future<void> apiLoadPreset({required AppConfig config}) =>
    RustLib.instance.api.crateApiSimpleApiLoadPreset(config: config);

Future<void> apiTriggerTestError({required String message}) =>
    RustLib.instance.api.crateApiSimpleApiTriggerTestError(message: message);

Future<int> apiGetAudioFileChannels({required String filePath}) => RustLib
    .instance
    .api
    .crateApiSimpleApiGetAudioFileChannels(filePath: filePath);

Future<void> apiApplyAllChannelTunings({
  required List<ChannelTuningParams> tunings,
}) => RustLib.instance.api.crateApiSimpleApiApplyAllChannelTunings(
  tunings: tunings,
);

Future<void> apiApplyChannelTuning({
  required int channel,
  required double delayMs,
  required List<EqBand> eqBands,
}) => RustLib.instance.api.crateApiSimpleApiApplyChannelTuning(
  channel: channel,
  delayMs: delayMs,
  eqBands: eqBands,
);

Future<void> apiApplyGlobalTuning({
  required double masterHeadroomDb,
  required bool peakLimiterEnabled,
}) => RustLib.instance.api.crateApiSimpleApiApplyGlobalTuning(
  masterHeadroomDb: masterHeadroomDb,
  peakLimiterEnabled: peakLimiterEnabled,
);

Future<void> apiUpdateSpatialConfigJson({required String jsonPayload}) =>
    RustLib.instance.api.crateApiSimpleApiUpdateSpatialConfigJson(
      jsonPayload: jsonPayload,
    );

Future<Point3D> apiCalculateBezierPoint({
  required double t,
  required Point3D p0,
  required Point3D p1,
  required Point3D p2,
  required Point3D p3,
}) => RustLib.instance.api.crateApiSimpleApiCalculateBezierPoint(
  t: t,
  p0: p0,
  p1: p1,
  p2: p2,
  p3: p3,
);

Future<Float32List> apiCalculateDbapHeatmap({
  required Point3D listenerPos,
  required List<Point3D> channelPositions,
}) => RustLib.instance.api.crateApiSimpleApiCalculateDbapHeatmap(
  listenerPos: listenerPos,
  channelPositions: channelPositions,
);

Float32List apiCalculateEqResponseCurve({
  required List<EqBand> bands,
  required BigInt numPoints,
  required double sampleRate,
}) => RustLib.instance.api.crateApiSimpleApiCalculateEqResponseCurve(
  bands: bands,
  numPoints: numPoints,
  sampleRate: sampleRate,
);

class ChannelTuningParams {
  final int channel;
  final double delayMs;
  final List<EqBand> eqBands;

  const ChannelTuningParams({
    required this.channel,
    required this.delayMs,
    required this.eqBands,
  });

  @override
  int get hashCode => channel.hashCode ^ delayMs.hashCode ^ eqBands.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChannelTuningParams &&
          runtimeType == other.runtimeType &&
          channel == other.channel &&
          delayMs == other.delayMs &&
          eqBands == other.eqBands;
}

class EngineStateUpdate {
  final String? activeRoomId;
  final bool duckingActive;
  final List<String> playingTrackIds;
  final String? engineError;
  final int outputChannelCount;

  const EngineStateUpdate({
    this.activeRoomId,
    required this.duckingActive,
    required this.playingTrackIds,
    this.engineError,
    required this.outputChannelCount,
  });

  @override
  int get hashCode =>
      activeRoomId.hashCode ^
      duckingActive.hashCode ^
      playingTrackIds.hashCode ^
      engineError.hashCode ^
      outputChannelCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineStateUpdate &&
          runtimeType == other.runtimeType &&
          activeRoomId == other.activeRoomId &&
          duckingActive == other.duckingActive &&
          playingTrackIds == other.playingTrackIds &&
          engineError == other.engineError &&
          outputChannelCount == other.outputChannelCount;
}

class OutputDeviceInfo {
  final String name;
  final int maxChannels;
  final List<String> channelNames;

  const OutputDeviceInfo({
    required this.name,
    required this.maxChannels,
    required this.channelNames,
  });

  @override
  int get hashCode =>
      name.hashCode ^ maxChannels.hashCode ^ channelNames.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OutputDeviceInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          maxChannels == other.maxChannels &&
          channelNames == other.channelNames;
}
